## The Python Programming language: Functions

In [1]:
x  = 1
y = 2
x+y

3

In [2]:
x

1

In [3]:
def add_numbers(x,y):
    return x+y
add_numbers(1,2)

3

In [4]:
def add_numbers(x, y, z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
print(add_numbers(1, 2, 3))
print(add_numbers(1, 2))

6
3


In [5]:
def add_numbers(x, y, z=None,flag=False):
    if(flag==True):
        print("Flag is true!")
    if(z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1,2,3,flag=True))
print(add_numbers(1,2,flag=True))
print(add_numbers(1,2,3))

Flag is true!
6
Flag is true!
3
6


In [6]:
add_numbers(1, 2,True)

4

In [7]:
add_numbers(1, 2, 3, True)

Flag is true!


6

## The Python Programming Language: Types and Sequences

In [8]:
type("This is a string")

str

In [9]:
type(None)

NoneType

In [10]:
type(True)

bool

In [11]:
type(False)

bool

In [12]:
type(def)

SyntaxError: invalid syntax (<ipython-input-12-68a504197283>, line 1)

In [13]:
type(1)

int

In [14]:
type(1.0)

float

In [15]:
type(add_numbers)

function

In [16]:
x = (1,'a',2,'b')
type(x)

tuple

In [17]:
x = [1,2,'a','b']
type(x)

list

In [18]:
x.append(3.3)

In [19]:
print(x)

[1, 2, 'a', 'b', 3.3]


In [20]:
for item in x:
    print(item)

1
2
a
b
3.3


In [21]:
i = 0
while(i != len(x)):
    print(x[i])
    i+=1

1
2
a
b
3.3


In [22]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [23]:
[1,2]*2

[1, 2, 1, 2]

In [24]:
[1] in [1,2,3]

False

In [25]:
1 in [1,2,3]

True

In [26]:
x = "This is string"
print(x[0])
print(x[0:1])
print(x[0:2])

T
T
Th


In [27]:
x[-1]

'g'

In [28]:
x[-4:-2]

'ri'

In [29]:
x[:3]

'Thi'

In [30]:
x[3:]

's is string'

In [31]:
x[:]

'This is string'

In [32]:
firstname = "harsha"
lastname = "apoorv"
print(firstname+' '+lastname)
print(firstname*3)
print('har' in firstname)

harsha apoorv
harshaharshaharsha
True


In [33]:
firstname = "Merapureddy Harsha apoorv".split()[0]
lastname  = "Merapureddy Harsha apoorv".split()[1]
print(firstname)
print(lastname)

Merapureddy
Harsha


In [34]:
firstname = "Merapureddy Harsha apoorv".split()[0]
lastname  = "Merapureddy Harsha apoorv".split()[-1]
print(firstname)
print(lastname)

Merapureddy
apoorv


In [35]:
x = {'Harshaapoorv':"harshaapoorva164@gmail.com",'hagajxc':'harshaapoorv0@gmail.com'}
x['Harshaapoorv']

'harshaapoorva164@gmail.com'

In [36]:
x['naakutheleenodu']=None
print(x['naakutheleenodu'])

None


In [37]:
for name in x:
    print(x[name])
    print(name)

harshaapoorva164@gmail.com
Harshaapoorv
harshaapoorv0@gmail.com
hagajxc
None
naakutheleenodu


In [38]:
for name in x:
    print(name,end=':')
    print(x[name])

Harshaapoorv:harshaapoorva164@gmail.com
hagajxc:harshaapoorv0@gmail.com
naakutheleenodu:None


In [39]:
for mails in x.values():
    print(mails)

harshaapoorva164@gmail.com
harshaapoorv0@gmail.com
None


In [40]:
for names in x.keys():
    print(names)

Harshaapoorv
hagajxc
naakutheleenodu


In [41]:
for names in x:
    print(names)

Harshaapoorv
hagajxc
naakutheleenodu


In [42]:
for pairs in x.items():
    print(pairs)

('Harshaapoorv', 'harshaapoorva164@gmail.com')
('hagajxc', 'harshaapoorv0@gmail.com')
('naakutheleenodu', None)


In [43]:
for name,mail in x.items():
    print(name)
    print(mail)

Harshaapoorv
harshaapoorva164@gmail.com
hagajxc
harshaapoorv0@gmail.com
naakutheleenodu
None


In [44]:
print(name)

naakutheleenodu


In [45]:
print(mail)

None


In [46]:
_+"baboi"

'harshaapoorva164@gmail.combaboi'

In [47]:
-+" "+"baboi"

TypeError: bad operand type for unary +: 'str'

In [48]:
_+" "+"baboi"

'harshaapoorva164@gmail.combaboi baboi'

## Unpacking

In [49]:
x = ('harsha','apoorv','harshaapoorva164@gmail.com')
fname,lname,email = x

In [50]:
fname

'harsha'

In [51]:
lname

'apoorv'

In [52]:
email

'harshaapoorva164@gmail.com'

In [53]:
x = ('harsha','apoorv','harshaapoorva164@gmail.com','Tadepalligudem')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

In [54]:
fname, lname, email, place  = x

In [55]:
place

'Tadepalligudem'

In [56]:
fname

'harsha'

In [57]:
lnmae

NameError: name 'lnmae' is not defined

In [58]:
lname

'apoorv'

In [59]:
email

'harshaapoorva164@gmail.com'

## The Python Programming Language: More on strings

In [60]:
"harsha"+2

TypeError: can only concatenate str (not "int") to str

In [61]:
"harsha"+str(2)

'harsha2'

In [62]:
print("harsha"+str(2))

harsha2


In [63]:

print("harsha"+2)

TypeError: can only concatenate str (not "int") to str

In [64]:
sales_record = {'price':24,
               'num_items':4,
               'person':'larypage'}
sales_statement = "{} bought {} items at {} for a total of {}"
print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['price']*sales_record['num_items']))

larypage bought 4 items at 24 for a total of 96


In [65]:
sales_record = {'price':24,
               'num_items':4,
               'person':'Larrypage'}
sales_statement = "{} bought {} items at {} for a total of {}"
print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['price']*sales_record['num_items']))

Larrypage bought 4 items at 24 for a total of 96


In [66]:
sales_record = {'price':24,
               'num_items':4,
               'person':'Larrypage'}
sales_statement = "{} bought {} items at a price of {} for a total of {}"
print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['price']*sales_record['num_items']))

Larrypage bought 4 items at a price of 24 for a total of 96


## Data Files and Summary statistics

In [67]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [68]:
mact = mpg[:3]
count = 0
for manu in mact['manufacturer']:
    if mact['manufacturer']=="audi":
        count+=1
print(count)

TypeError: list indices must be integers or slices, not str

In [69]:
mact = mpg[:3]
count = 0
for manu in mact:
    if manu['manufacturer']=="audi":
        count+=1
print(count)

3


In [70]:
mapt = mpg
audicount = 0
for mafu in mapt:
    if mafu['manufacturer']=="audi":
        audicount+=1
print(audicount)

18


In [71]:
for i in range(len(mapt)):
    print(mapt[i]['manufacturer'])
    

audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
honda
honda
honda
honda
honda
honda
honda
honda
honda
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
jeep
jeep
jeep
jeep
jeep
jeep
jeep
jeep
land rover
land rover
land rover
land rover
lincoln
lincoln
lincoln
mercury
mercury
mercury
mercury
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
niss

In [72]:
manulist = list()
for i in range(len(mapt)):
    #print(mapt[i]['manufacturer'])
    if mapt[i]['manufacturer'] in manulist:
        continue
    else:
        manulist.append(mapt[i]['manufacturer'])
print(manulist)
    

['audi', 'chevrolet', 'dodge', 'ford', 'honda', 'hyundai', 'jeep', 'land rover', 'lincoln', 'mercury', 'nissan', 'pontiac', 'subaru', 'toyota', 'volkswagen']


In [73]:
manulist = list()
totlist = list()
for i in range(len(mapt)):
    #print(mapt[i]['manufacturer'])
    a = mapt[i]['manufacturer']
    if a in manulist:
        totlist.append(a)
        continue
    else:
        manulist.append(a)
print(manulist)
#print(totlist)
    

['audi', 'chevrolet', 'dodge', 'ford', 'honda', 'hyundai', 'jeep', 'land rover', 'lincoln', 'mercury', 'nissan', 'pontiac', 'subaru', 'toyota', 'volkswagen']


In [74]:
for i in manulist:
    cont = totlist.count(i)
    print(i,"has manufactured",cont,"models")

audi has manufactured 17 models
chevrolet has manufactured 18 models
dodge has manufactured 36 models
ford has manufactured 24 models
honda has manufactured 8 models
hyundai has manufactured 13 models
jeep has manufactured 7 models
land rover has manufactured 3 models
lincoln has manufactured 2 models
mercury has manufactured 3 models
nissan has manufactured 12 models
pontiac has manufactured 4 models
subaru has manufactured 13 models
toyota has manufactured 33 models
volkswagen has manufactured 26 models


In [75]:
countlist = []
cont = 0
maxcont = 0
for i in manulist:
    cont = totlist.count(i)
    if cont>maxcont:
        maxter = i
    countlist.append(cont)
print(maxter,"has manufactureded highest number of models with",max(countlist),"models")

volkswagen has manufactureded highest number of models with 36 models


In [76]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
print(mpg[:3])

[{'': '1', 'manufacturer': 'audi', 'model': 'a4', 'displ': '1.8', 'year': '1999', 'cyl': '4', 'trans': 'auto(l5)', 'drv': 'f', 'cty': '18', 'hwy': '29', 'fl': 'p', 'class': 'compact'}, {'': '2', 'manufacturer': 'audi', 'model': 'a4', 'displ': '1.8', 'year': '1999', 'cyl': '4', 'trans': 'manual(m5)', 'drv': 'f', 'cty': '21', 'hwy': '29', 'fl': 'p', 'class': 'compact'}, {'': '3', 'manufacturer': 'audi', 'model': 'a4', 'displ': '2', 'year': '2008', 'cyl': '4', 'trans': 'manual(m6)', 'drv': 'f', 'cty': '20', 'hwy': '31', 'fl': 'p', 'class': 'compact'}]


In [77]:
mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [78]:
len(mpg)

234

In [79]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [80]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [81]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [82]:
manufacturers = list(set(d['manufacturer'] for d in mpg))
manufacturers

['jeep',
 'land rover',
 'audi',
 'subaru',
 'hyundai',
 'nissan',
 'pontiac',
 'mercury',
 'lincoln',
 'honda',
 'ford',
 'dodge',
 'toyota',
 'chevrolet',
 'volkswagen']

In [83]:
cylinders = set(d['cyl'] for d in mpg)
print(sorted(list(cylinders)))
cylinders

['4', '5', '6', '8']


{'4', '5', '6', '8'}

In [84]:
CtympgCyl = []
for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl']==c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtympgCyl.append((c,summpg / cyltypecount))
CtympgCyl.sort(key=lambda x:x[0])
CtympgCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [85]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [86]:
HwyMpgByClass = []

for cls in vehicleclass:
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class']==cls:
            summpg += float(d['hwy'])
            vclasscount += 1
    HwyMpgByClass.append((cls, summpg / vclasscount))
HwyMpgByClass.sort(key=lambda x:x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

## The Python Programming Language: Dates and Times

In [87]:
import datetime as dt
import time as tm

In [88]:
tm.time()

1600266640.23

In [89]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [90]:
dtnow

datetime.datetime(2020, 9, 16, 20, 0, 40, 978384)

In [91]:
dtnow.year,dtnow.month,dtnow.day

(2020, 9, 16)

In [92]:
dtnow.hour,dtnow.minute,dtnow.second

(20, 0, 40)

In [93]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [94]:
today = dt.date.today()

In [95]:
today-delta

datetime.date(2020, 6, 8)

In [96]:
today > today-delta

True

## The Python Programming language: Objects and map()

In [97]:
class Person:
    department = "Engineering"
    
    def set_name(self,new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location
    def set_department(self,new_department):
        self.department = new_department

In [98]:
person = Person()
person.department

'Engineering'

In [99]:
person.set_name("Harsha")
person.set_department("CSE")

In [100]:
print(person.name)
person.department

Harsha


'CSE'

In [101]:
person.set_location("Tadepalligudem")

In [102]:
detail = "{} lives in {} from {} department"
print(detail.format(person.name,
                   person.location,
                   person.department))

Harsha lives in Tadepalligudem from CSE department


In [103]:
secondperson = Person()

In [104]:
secondperson.set_name("apoorv")
secondperson.set_location("Tadepalligudem")
seconddetail = "{} lives in {} from {} department"
print(seconddetail.format(secondperson.name,
                         secondperson.location,
                         secondperson.department))

apoorv lives in Tadepalligudem from Engineering department


In [105]:
person

In [106]:
print(person)

In [107]:
store1 = [10.00,9.34,5.67,10.21,11.00,6]
store2 = [6.21,4.32,8.92,6.61,2.21,3.31]
cheapest = map(min, store1, store2)
cheapest

In [108]:
people = ["Dr. Chuck severnece","Dr. Chris Brooke","Dr. Larry Page"]

def split_name_and_title(person):
    title = person.split()[0]
    firstname = person.split()[-1]
    return "{} {}".format(title,firstname)
person = list(map(split_name_and_title,people))
print(person)

['Dr. severnece', 'Dr. Brooke', 'Dr. Page']


In [109]:
type(lambda x:x+1)

function

## The Python Programming Language: Lambdas and List Comprehensions

In [110]:
my_function = lambda a,b,c : a+b

In [111]:
my_function(1,2,3)

3

In [112]:
my_list = []
for number in range(0,1000):
    if number%2==0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [113]:
my_list = [number for number in range(1000) if number%2==0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [114]:
lowercase = "abcdefghijklmnopqrstuvwxyz"
digits = "0123456789"
answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
answer

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49',
 'aa50',
 'aa51',
 'aa52',
 'aa53',
 'aa54',
 'aa55',
 'aa56',
 'aa57',
 'aa58',
 'aa59',
 'aa60',
 'aa61',
 'aa62',
 'aa63',
 'aa64',
 'aa65',
 'aa66',
 'aa67',
 'aa68',
 'aa69',
 'aa70',
 'aa71',
 'aa72',
 'aa73',
 'aa74',
 'aa75',
 'aa76',
 'aa77',
 'aa78',
 'aa79',
 'aa80',
 'aa81',
 'aa82',
 'aa83',
 'aa84',
 'aa85',
 'aa86',
 'aa87',
 'aa88',
 'aa89',
 'aa90',
 'aa91',
 'aa92',
 'aa93',
 'aa94',
 'aa95',
 'aa96',
 'aa97',
 'aa98',
 'aa99',
 'ab00',
 'ab01',
 'ab02',
 'ab03',
 'ab04',
 'ab05',
 'ab06',
 'ab07',
 'ab08',
 'ab09',
 'ab10',
 

In [115]:
len(answer)

67600

# Numpy

In [116]:
import numpy as np


## Creating Arrays

In [117]:
my_list = [1,2,3]
x = np.array(my_list)
x

array([1, 2, 3])

In [118]:
type(x)

numpy.ndarray

In [119]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [120]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
m.shape # returns the shape of the array

(2, 3)

In [122]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [123]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [124]:
n.reshape(5,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [125]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [126]:
o.resize(3,3)

In [127]:
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [128]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [132]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [133]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [134]:
p = np.ones([2,3],int)

In [135]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [136]:
np.vstack([p,2*p])


array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [137]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [138]:
x+y

array([5, 7, 9])

In [139]:
x * y

array([ 4, 10, 18])

In [140]:
x**2

array([1, 4, 9], dtype=int32)

In [141]:
x.dot(y)

32

In [142]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [143]:
np.array([y, y**2])

array([[ 4,  5,  6],
       [16, 25, 36]])

In [144]:
z.shape

(2, 3)

In [145]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [146]:
z.shape

(2, 3)

In [147]:
q = z.T
q

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [148]:
q.shape

(3, 2)

In [149]:
z.T.shape

(3, 2)

In [150]:
z.dtype

dtype('int32')

In [151]:
z = z.astype('f')
z.dtype

dtype('float32')

In [152]:
a  = np.array([-4, -2, 1, 3, 5])

In [153]:
a.sum()

3

In [154]:
a.max()

5

In [155]:
a.min()

-4

In [156]:
a.mean()

0.6

In [157]:
a.std()

3.2619012860600183

In [158]:
a.argmax()

4

In [159]:
a.argmin()

0

## Indexing/Slicing

In [160]:
s = np.arange(13)**2

In [161]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [162]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [163]:
s[0]
s[4]
s[0:3]

array([0, 1, 4], dtype=int32)

In [164]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [165]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [166]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [167]:
r = np.arange(36)
r = r.reshape((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [168]:
r[2, 2]

14

In [169]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [170]:
r[2,2]

14

In [171]:
r[3,3:6]

array([21, 22, 23])

In [172]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [173]:
r[-1,::2]

array([30, 32, 34])

In [174]:
r[r>30]

array([31, 32, 33, 34, 35])

In [175]:
r[r<5]

array([0, 1, 2, 3, 4])

In [176]:
r[r==5]

array([5])

In [177]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [178]:
r2 = r[:3,:3]

In [179]:
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [180]:
r2[:]=0

In [181]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [182]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [183]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [184]:
r_copy[:]=10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [185]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Iterating Over Arrays

In [186]:
test = np.random.randint(0, 10, (4, 3))
test

array([[9, 3, 2],
       [7, 0, 7],
       [0, 0, 0],
       [2, 4, 9]])

In [187]:
for row in test:
    print(row)

[9 3 2]
[7 0 7]
[0 0 0]
[2 4 9]


In [188]:
for i in range(len(test)):
    print(test[i])

[9 3 2]
[7 0 7]
[0 0 0]
[2 4 9]


In [189]:
for i, row in enumerate(test):
    print("row",i,"is",row)

row 0 is [9 3 2]
row 1 is [7 0 7]
row 2 is [0 0 0]
row 3 is [2 4 9]


In [190]:
test2 = test**2

In [191]:
test2

array([[81,  9,  4],
       [49,  0, 49],
       [ 0,  0,  0],
       [ 4, 16, 81]], dtype=int32)

In [192]:
for i, j in zip(test, test2):
    print(i,"+",j,"=",i+j)

[9 3 2] + [81  9  4] = [90 12  6]
[7 0 7] + [49  0 49] = [56  0 56]
[0 0 0] + [0 0 0] = [0 0 0]
[2 4 9] + [ 4 16 81] = [ 6 20 90]
